db.host=gestion-hotel-mysql-g3stion-h0t3l-12a6.i.aivencloud.com

db.port=27209

db.name=defaultdb

db.user=avnadmin

db.password=AVNS_AzbBvXWJ3zMGbvlP_kA

db.ssl.mode=REQUIRED
db.public.key.retrieval=true
