@startuml
actor "Réceptionniste" as User
participant "Système" as System

User -> System : Demande de création de réservation (Client, Chambre, Dates)
activate System

System -> System : Vérifier disponibilité chambre
alt Chambre occupée
    System --> User : Erreur : Chambre indisponible
else Chambre libre
    System -> System : Récupérer liste services actifs
    System --> User : Affiche formulaire complété avec services
    
    User -> System : Confirme réservation avec Services
    System -> System : Enregistrer Réservation
    System --> User : Confirmation création (ID Réservation)
end

deactivate System
@enduml
