@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Réceptionniste" as Rec
actor "Administrateur" as Admin

' Inheritance
Admin --|> Rec

package "Authentification" {
    usecase "Se connecter" as Login
    usecase "Se déconnecter" as Logout
    usecase "Gérer son Profil / Changer MDP" as Settings
}

package "Administration Système" {
    usecase "Gérer les Utilisateurs (Comptes)" as ManageUsers
    usecase "Gérer les Employés (RH)" as ManageEmployees
}

' Links
Rec --> Login
Rec --> Logout
Rec --> Settings

' Admin exclusive
Admin --> ManageUsers
Admin --> ManageEmployees

note "Seul l'Administrateur peut gérer\nles comptes et les employés." as N1
ManageUsers .. N1

@enduml
